### ISSUE TITLE
Technical Story: Investigation on InfluxDB as the database.

### ISSUE THREAD

**Issue by Ricardo-1894** [gcivil-nyu-org/spring2020-cs-gy-9223-backend#33]
**Technical story:**
The InfluxDB seems to support Grafana very well, therefore backend team need to investigate the compatibility

**Acceptance criteria:**
* Easy sync
* Compatible with Django
* Support Grafana

**Definition of Done:**
1. If the plan proved work, the entire workplan can be implemented.

**Other information:**
https://grafana.com/docs/grafana/latest/features/datasources/influxdb/
https://grafana.com/blog/2019/11/06/how-to-stream-sensor-data-with-grafana-and-influxdb/
https://www.influxdata.com/products/influxdb-overview/
https://stackoverflow.com/questions/50198741/django-influxdb
https://stackoverflow.com/questions/25212009/django-postgres-large-time-series/32641215#32641215

**Comment by Ziheng-Wang** [comment]
[https://www.influxdata.com/time-series-database/](url)

**Comment by Ziheng-Wang** [comment]
Benefits of using InfluxDB in our project : 
1. Time series databases have key architectural design properties that make them very different from other databases. These include time-stamp data storage and compression, data lifecycle management, data summarization, ability to handle large time series dependent scans of many records and time series aware queries.(This is very important when we wanna fetch data in a period of time from database).
2. It's compatible with Django
