### ISSUE TITLE
Technical Story: Investigation on PostgreSql as the database.

### ISSUE THREAD

**Issue by Ricardo-1894** [gcivil-nyu-org/spring2020-cs-gy-9223-backend#36]
**User story**
Another database choice is PostgreSQL. Comparing to other DBMS options, I wonder if this will be a good choice for the project.

**Acceptance criteria**
* Easy sync
* Compatible with Django
* Development complexity
* Support Grafana

**Definition of Done**
1. Working demo on how it is used in a mockup Django project, analytics of how PostgreSQL will fit into the project.

**Comment by alldne** [comment]
How to sync postgresql
https://dba.stackexchange.com/a/170991

**Comment by alldne** [comment]
Because the former mercury team used postgresql, I believe it automatically satisfies the following:

- Compatible with Django
- Support Grafana

When it comes to development complexity, I think postgresql should be basline that can be compared to other candidates i.e influxdb, mongodb.

**Comment by jackxujh** [comment]
> When it comes to development complexity, I think postgresql should be basline that can be compared to other candidates i.e influxdb, mongodb.

Excellent point about the baseline!

**Comment by alldne** [comment]
I'm working on this document

https://docs.google.com/document/d/1fC4UWeljFhnIgNNg6nH99x5EswGRWqLqdfTDkYfuk4o/edit#
