### ISSUE TITLE
Tech Story: Meet with Hardware team to design data protocol

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/spring2020-cs-gy-9223-backend#42]

**Comment by VentusXu09** [comment]
For the current stage, we will use pySerial to set the listening port and the json body format will be:
{
	sensors:{
		ss_id : “Sensor id”,
		ss_value : {
			/*as many values as you wish*/
			value_a_name : “value_a”,
			value_b_name : “value_b”,
			value_c_name : “value_c”
		}
		Date : “2014-03-12T13:37:27+00:00” /*ISO 8601 dates*/
	}
}
